name: Kubescape
on: [push]
jobs:
  nsa-security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Kubescape
        run: |
          curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash
          export PATH=$PATH:/path/to/kubescape/directory
      - name: Scan YAML files
        run: |
          kubescape scan framework nsa *.yaml
