
name: demo workflow
 
on:
  push:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    strategy:
     matrix:
      python-version: ["3.8","3.9","3.12"]
     
 
    env:
      first_name : "Gaurav"
 
    steps:
      - name: my name
        run: echo ${{ env.first_name}}
 
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content
 
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }} # install the python version needed
 
      - name: execute py script # run main.py
        run: python addition.py
 
      - name: Run a one-line script
        run: echo Hello, World!
 
      - name: Run multi-line script
        run: |
             echo This is my work.
             echo Submitted to you.  
